### PR TITLE
Enable decoding of 'mixed' page types in a single column row group

### PR DESCRIPTION
**Pull request by nregenauer**
I recently faced an issue where I needed to decode a Parquet file that had been encoded for reads with Amazon Athena. 

This file had a mixture of 'PLAIN' and 'PLAIN_DICTIONARY' pages in it; when decoding, I noticed an issue where all records from the 'PLAIN' groups were being set to unknown.

The commit below is a quick fix for this issue; possibly the *correct* long term fix is to enable this library to support different Parquet versions?

### CODE REVIEW

**Comment by nregenauer** [comment]
Just checking in to see if you've gotten a chance to take a look at this change

**Comment by Acen** [comment]
Nice work @nregenauer 
@ZJONSSON could you give the PR a quick once-over?

**Comment by ZJONSSON** [comment]
Thanks @nregenauer - do you have a test case / test file with mixed pages that would fail before this fi?

**Comment by nregenauer** [comment]
Sorry about the delayed response - I've done some more thorough testing of this change and I'm not confident that it's non-breaking (it seems to be a step in the right direction, but not a perfect fix). 

Previously, on my local test cases I was seeing issues where ~half the records in large files (on the order of 27-30 MB) were blank. After merging this change, records were no longer blank; however, a random percentage of records in the file had one or more fields "swapped" (RecordX contained value Y for attribute A, the value that should have been assigned to RecordZ). This issue appeared to affect ~10-20% of the total records in any given file.

Since this PR doesn't *fully* resolve this issue, I'm going to close for now - if I get the bandwidth I'll revisit and add test cases.

**Pull request closed without merging**
