### PR TITLE
Use bigint for int64

### PR DESCRIPTION
**Pull request by krasic**
Test updates for this are TBD.

### CODE REVIEW

**Comment by krasic** [comment]
Tests pass now.

**Comment by krasic** [comment]
For some context.   parquet files generated by presto, spark, etc. can have int64 values.   Node v12 has bigint, and buffer/bigint conversions, that make fully supporting int64 in parquetjs fairly straightforward.

**Comment by ZJONSSON** [comment]
Thanks @krasic, much appreciated.  Will take a look

**Comment by krasic** [comment]
Friendly ping.

**Comment by jeffbski-rga** [comment]
BigInt is supported in Node 10.4.0+ so this would be better than using node-int64 which is not maintained.

**Comment by jeffbski-rga** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt

**Comment by krasic** [comment]
@jeffbski-rga Thanks for looking.  I had already moved this over to use BigInt, and dropped node-int64.

**Comment by jeffbski-rga** [comment]
@krasic I was just commenting for this PR, in case Ziggy and the maintainers weren't aware of when it was available in Node.js.

**Comment by ZJONSSON** [comment]
Excellent, thanks @krasic  @jeffbski-rga

**Comment by ZJONSSON** [comment]
Also published here from the parquetjs-lite branch: `+ parquetjs-lite@0.8.6`

**Pull request merged**
