### PR TITLE
Added ENUM to types

### PR DESCRIPTION
**Pull request by Aletheios**
I'm no parquet file expert but the ENUM type was missing when I tried to read my local parquet files with this library. The type seems to be synonymous to UTF8...

### CODE REVIEW

**Comment by ZJONSSON** [comment]
Excellent, thank you @Aletheios    Would you mind adding a test case - or sharing a parquet file that would be good for testing?

**Comment by Aletheios** [comment]
@ZJONSSON I've added a test file and a small test case. Unfortunately I'm not allowed to share the real files I'm using.

**Comment by ZJONSSON** [comment]
Perfect, thank you!!

**Comment by ZJONSSON** [comment]
Perfect, thank you!!

**Pull request merged**
